//! Groove faithfulness — THE PHASE 2 EXIT CRITERION.
//!
//! The arranger used to *gate* events against a template: on real beatbox, 16
//! detected events collapsed to a single drum note. Spec §4.3 replaced gating
//! with deterministic fidelity placement — at fidelity 1.0 every detected
//! drum-class event must survive as a note that cites it via `source_event_id`.
//!
//! Two fixtures exercise the same >= 90% provenance-based survival assertion:
//!   - `real-beatbox-2.wav` — a gitignored human recording; skip-guarded so CI
//!     (generated fixtures only) passes while local runs enforce it.
//!   - `test-offgrid.wav` — a CI-enforced twin (generated by
//!     scripts/generate-test-audio.mjs): a kick/snare/hihat pattern whose every
//!     hit is offset +37ms off every template slot. No skip guard: this is the
//!     regression fence against the "arranger discards your performance" bug.

use std::fs;
use std::path::{Path, PathBuf};

use beatrice_lib::arranger::{arrange_events, ArrangementTemplate, Arrangement};
use beatrice_lib::audio::{self, OnsetConfig};
use beatrice_lib::events::{self, EventClass, HeuristicClassifier};
use beatrice_lib::groove::{
    self, Grid, GridDivision, GrooveFeel, QuantizeSettings, QuantizedEvent, TimeSignature,
};
use beatrice_lib::themes::Theme;

fn test_audio_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("test-audio")
}

/// Run the full detect -> classify -> tempo -> quantize -> grid pipeline on a WAV,
/// mirroring `pipeline_integration.rs::test_pattern_full_pipeline`.
/// Returns the quantized events, the phase-anchored grid, and the default theme.
fn run_pipeline(path: &Path) -> (Vec<QuantizedEvent>, Grid, Theme) {
    let bytes = fs::read(path).unwrap_or_else(|e| panic!("read {}: {}", path.display(), e));
    let audio = audio::ingest_wav(&bytes).unwrap_or_else(|e| panic!("parse wav: {}", e));

    let config = OnsetConfig::default();
    let onsets = audio::detect_onsets(&audio, &config);

    let classifier = HeuristicClassifier::new();
    let mut detected = Vec::new();
    for (i, onset) in onsets.iter().enumerate() {
        let dur = if i + 1 < onsets.len() {
            onsets[i + 1].timestamp_ms - onset.timestamp_ms
        } else {
            audio.duration_ms as f64 - onset.timestamp_ms
        };
        let win = dur.clamp(50.0, 500.0);
        let features = audio::extract_features_for_window(&audio, onset.timestamp_ms, win);
        let result = classifier.classify(&features);
        detected.push(events::Event::new(
            onset.timestamp_ms,
            dur,
            result.class,
            result.confidence,
            features,
        ));
    }

    let tempo = groove::estimate_tempo(&onsets, audio.sample_rate);
    let grid = Grid::with_phase(
        tempo.bpm,
        TimeSignature::FourFour,
        GridDivision::Sixteenth,
        GrooveFeel::Straight,
        0.0,
        4,
        tempo.phase_offset_ms,
    );
    let settings = QuantizeSettings {
        strength: 0.8,
        swing_amount: 0.0,
        lookahead_ms: 100.0,
    };
    let quantized = groove::quantize_events(&detected, &grid, &settings);

    let theme = beatrice_lib::themes::get_theme("BLADE RUNNER").expect("default theme");
    (quantized, grid, theme)
}

/// Fraction of detected drum-class events that produced a note citing them via
/// `source_event_id` within 30ms of their quantized time. Provenance-based, not
/// timestamp-coincidence — the note must be *traceable* to the event.
fn survival_rate(quantized: &[QuantizedEvent], arr: &Arrangement) -> (usize, usize) {
    let drum_events: Vec<&QuantizedEvent> = quantized
        .iter()
        .filter(|q| {
            matches!(
                q.original_event.class,
                EventClass::BilabialPlosive | EventClass::Click | EventClass::HihatNoise
            )
        })
        .collect();

    let survived = drum_events
        .iter()
        .filter(|q| {
            arr.drum_lanes.iter().any(|l| {
                l.events.iter().any(|n| {
                    n.source_event_id == Some(q.original_event.id)
                        && (n.timestamp_ms - q.quantized_timestamp_ms).abs() < 30.0
                })
            })
        })
        .count();

    (survived, drum_events.len())
}

#[test]
fn real_beatbox_2_events_survive_at_full_fidelity() {
    let path = test_audio_dir().join("real-beatbox-2.wav");
    if !path.exists() {
        eprintln!("skipping real_beatbox_2: fixture absent (gitignored human recording)");
        return;
    }

    let (quantized, grid, theme) = run_pipeline(&path);
    // Base arrangement (pre song-expansion) so source_event_id maps 1:1.
    let arr = arrange_events(
        &quantized,
        &ArrangementTemplate::SynthwaveStraight,
        &grid,
        &theme,
        0.6,
        1.0,
    );

    let (survived, total) = survival_rate(&quantized, &arr);
    assert!(total > 0, "no drum-class events detected");
    let rate = survived as f64 / total as f64;
    assert!(
        rate >= 0.9,
        "only {:.0}% of events produced notes ({}/{}) (was ~7% before Phase 2)",
        rate * 100.0,
        survived,
        total
    );
}

#[test]
fn offgrid_events_survive_at_full_fidelity() {
    // CI-enforced twin. Every hit is +37ms off the grid — the exact case the old
    // template gate silently deleted. No skip guard: this must always hold.
    let path = test_audio_dir().join("test-offgrid.wav");
    let (quantized, grid, theme) = run_pipeline(&path);
    let arr = arrange_events(
        &quantized,
        &ArrangementTemplate::SynthwaveStraight,
        &grid,
        &theme,
        0.6,
        1.0,
    );

    // Diagnostic: events-in vs notes-out at each fidelity, contrasted with the old
    // template-gating behaviour this task replaced.
    let notes = |f: f32| -> usize {
        arrange_events(
            &quantized,
            &ArrangementTemplate::SynthwaveStraight,
            &grid,
            &theme,
            0.6,
            f,
        )
        .drum_lanes
        .iter()
        .map(|l| l.events.len())
        .sum()
    };
    let drum_in = quantized
        .iter()
        .filter(|q| {
            matches!(
                q.original_event.class,
                EventClass::BilabialPlosive | EventClass::Click | EventClass::HihatNoise
            )
        })
        .count();
    eprintln!(
        "OFFGRID: {} drum-class events in -> drum notes out: fidelity1.0={} fidelity0.8={} fidelity0.0={}",
        drum_in,
        notes(1.0),
        notes(0.8),
        notes(0.0),
    );

    let (survived, total) = survival_rate(&quantized, &arr);
    assert!(total > 0, "no drum-class events detected in test-offgrid.wav");
    let rate = survived as f64 / total as f64;
    assert!(
        rate >= 0.9,
        "only {:.0}% of off-grid events produced notes ({}/{}) — fidelity placement regressed to gating",
        rate * 100.0,
        survived,
        total
    );
}
