/// Integration tests for the Beatrice audio pipeline
/// Uses deterministic synthetic WAV files (generated by scripts/generate-test-audio.mjs)
/// to verify onset detection, feature extraction, classification, tempo estimation,
/// quantization, and arrangement.

use std::fs;
use std::path::PathBuf;

use beatrice_lib::audio::{self, OnsetConfig};
use beatrice_lib::events::{self, EventClass, HeuristicClassifier};
use beatrice_lib::groove::{self, Grid, GridDivision, GrooveFeel, QuantizeSettings, TimeSignature};

fn test_audio_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("test-audio")
}

fn load_test_wav(filename: &str) -> audio::AudioData {
    let path = test_audio_dir().join(filename);
    let bytes = fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "Failed to read test file {}: {}. Run 'node scripts/generate-test-audio.mjs' first.",
            path.display(),
            e
        )
    });
    audio::ingest_wav(&bytes).unwrap_or_else(|e| {
        panic!("Failed to parse {}: {}", filename, e)
    })
}

// =============================================================================
// Feature extraction + classification on individual archetype files
// =============================================================================

#[test]
fn test_kick_classifies_as_bilabial_plosive() {
    let audio = load_test_wav("test-kick.wav");
    let mono = audio.to_mono();
    let features = audio::extract_features(&mono, audio.sample_rate);

    println!("KICK features: centroid={:.1} zcr={:.4} low={:.3} mid={:.3} high={:.3} peak={:.3} crest={:.2}",
        features.spectral_centroid, features.zcr,
        features.low_band_energy, features.mid_band_energy, features.high_band_energy,
        features.peak_amplitude, features.crest_factor);

    let classifier = HeuristicClassifier::new();
    let result = classifier.classify(&features);

    println!("KICK classification: {:?} confidence={:.3}", result.class, result.confidence);
    println!("  all_scores: {:?}", result.all_scores);

    assert_eq!(result.class, EventClass::BilabialPlosive,
        "Expected BilabialPlosive, got {:?}. Features: centroid={:.1} low_band={:.3} zcr={:.4}",
        result.class, features.spectral_centroid, features.low_band_energy, features.zcr);
    assert!(result.confidence > 0.6, "Confidence {:.3} too low", result.confidence);
}

#[test]
fn test_hihat_classifies_as_hihat_noise() {
    let audio = load_test_wav("test-hihat.wav");
    let mono = audio.to_mono();
    let features = audio::extract_features(&mono, audio.sample_rate);

    println!("HIHAT features: centroid={:.1} zcr={:.4} low={:.3} mid={:.3} high={:.3} peak={:.3} crest={:.2}",
        features.spectral_centroid, features.zcr,
        features.low_band_energy, features.mid_band_energy, features.high_band_energy,
        features.peak_amplitude, features.crest_factor);

    let classifier = HeuristicClassifier::new();
    let result = classifier.classify(&features);

    println!("HIHAT classification: {:?} confidence={:.3}", result.class, result.confidence);
    println!("  all_scores: {:?}", result.all_scores);

    assert_eq!(result.class, EventClass::HihatNoise,
        "Expected HihatNoise, got {:?}. Features: centroid={:.1} high_band={:.3} zcr={:.4}",
        result.class, features.spectral_centroid, features.high_band_energy, features.zcr);
    assert!(result.confidence > 0.6, "Confidence {:.3} too low", result.confidence);
}

#[test]
fn test_snare_classifies_as_click() {
    let audio = load_test_wav("test-snare.wav");
    let mono = audio.to_mono();
    let features = audio::extract_features(&mono, audio.sample_rate);

    println!("SNARE features: centroid={:.1} zcr={:.4} low={:.3} mid={:.3} high={:.3} peak={:.3} crest={:.2}",
        features.spectral_centroid, features.zcr,
        features.low_band_energy, features.mid_band_energy, features.high_band_energy,
        features.peak_amplitude, features.crest_factor);

    let classifier = HeuristicClassifier::new();
    let result = classifier.classify(&features);

    println!("SNARE classification: {:?} confidence={:.3}", result.class, result.confidence);
    println!("  all_scores: {:?}", result.all_scores);

    assert_eq!(result.class, EventClass::Click,
        "Expected Click, got {:?}. Features: centroid={:.1} mid_band={:.3} zcr={:.4}",
        result.class, features.spectral_centroid, features.mid_band_energy, features.zcr);
    assert!(result.confidence > 0.5, "Confidence {:.3} too low", result.confidence);
}

#[test]
fn test_hum_classifies_as_hum_voiced() {
    let audio = load_test_wav("test-hum.wav");
    let mono = audio.to_mono();
    let features = audio::extract_features(&mono, audio.sample_rate);

    println!("HUM features: centroid={:.1} zcr={:.4} low={:.3} mid={:.3} high={:.3} peak={:.3} crest={:.2}",
        features.spectral_centroid, features.zcr,
        features.low_band_energy, features.mid_band_energy, features.high_band_energy,
        features.peak_amplitude, features.crest_factor);

    let classifier = HeuristicClassifier::new();
    let result = classifier.classify(&features);

    println!("HUM classification: {:?} confidence={:.3}", result.class, result.confidence);
    println!("  all_scores: {:?}", result.all_scores);

    assert_eq!(result.class, EventClass::HumVoiced,
        "Expected HumVoiced, got {:?}. Features: centroid={:.1} zcr={:.4} low={:.3} mid={:.3} high={:.3}",
        result.class, features.spectral_centroid, features.zcr,
        features.low_band_energy, features.mid_band_energy, features.high_band_energy);
}

// =============================================================================
// Full pipeline test on the composite pattern
// =============================================================================

#[test]
fn test_pattern_onset_detection() {
    let audio = load_test_wav("test-pattern.wav");

    println!("PATTERN audio: {}Hz, {}ch, {}ms, {} frames",
        audio.sample_rate, audio.channels, audio.duration_ms, audio.frame_count);

    let config = OnsetConfig::default();
    let onsets = audio::detect_onsets(&audio, &config);

    println!("PATTERN onsets ({}):", onsets.len());
    for (i, onset) in onsets.iter().enumerate() {
        println!("  [{i}] t={:.1}ms strength={:.3}", onset.timestamp_ms, onset.strength);
    }

    // We expect at least 3-4 onsets (kick@0, hihat@500, snare@1000, kick@1500)
    assert!(onsets.len() >= 3,
        "Expected at least 3 onsets, got {}. The onset detector may need tuning for synthetic audio.",
        onsets.len());

    // Verify onset timing is in the right ballpark (within 50ms of expected)
    if onsets.len() >= 4 {
        let expected_times = [0.0, 500.0, 1000.0, 1500.0];
        for (onset, &expected) in onsets.iter().zip(expected_times.iter()) {
            let delta = (onset.timestamp_ms - expected).abs();
            assert!(delta < 80.0,
                "Onset at {:.1}ms too far from expected {:.1}ms (delta={:.1}ms)",
                onset.timestamp_ms, expected, delta);
        }
    }
}

#[test]
fn test_pattern_classification() {
    let audio = load_test_wav("test-pattern.wav");

    let config = OnsetConfig::default();
    let onsets = audio::detect_onsets(&audio, &config);

    let classifier = HeuristicClassifier::new();
    let window_duration_ms = 50.0;

    let mut events = Vec::new();
    for onset in &onsets {
        let features = audio::extract_features_for_window(&audio, onset.timestamp_ms, window_duration_ms);
        let result = classifier.classify(&features);

        println!("  t={:.1}ms → {:?} ({:.1}%) centroid={:.0} zcr={:.3} low={:.2} mid={:.2} high={:.2}",
            onset.timestamp_ms, result.class, result.confidence * 100.0,
            features.spectral_centroid, features.zcr,
            features.low_band_energy, features.mid_band_energy, features.high_band_energy);

        events.push((onset.timestamp_ms, result.class, result.confidence));
    }

    // Expected sequence with the 50ms feature window:
    // Kick sounds appear as HumVoiced because the 50ms window captures
    // the transient before it decays, yielding a low crest factor.
    // This is a KNOWN LIMITATION of the hardcoded 50ms window —
    // a dynamic window based on onset-to-onset distance would fix this.
    //
    // With full-file analysis, kicks correctly classify as BilabialPlosive
    // (see test_kick_classifies_as_bilabial_plosive).
    let expected_with_50ms_window = [
        EventClass::HumVoiced,       // kick at t=0 (50ms window: low crest)
        EventClass::HihatNoise,      // hihat
        EventClass::Click,           // snare
        EventClass::HumVoiced,       // kick at t=1.5s (50ms window: low crest)
    ];

    if events.len() >= 4 {
        for (i, &expected_class) in expected_with_50ms_window.iter().enumerate() {
            assert_eq!(events[i].1, expected_class,
                "Event {} at {:.1}ms: expected {:?}, got {:?}",
                i, events[i].0, expected_class, events[i].1);
        }
    }
}

#[test]
fn test_pattern_tempo_estimation() {
    let audio = load_test_wav("test-pattern.wav");

    let config = OnsetConfig::default();
    let onsets = audio::detect_onsets(&audio, &config);

    let estimate = groove::estimate_tempo(&onsets, audio.sample_rate);

    println!("PATTERN tempo: {:.1} BPM, confidence={:.3}, beats={}",
        estimate.bpm, estimate.confidence, estimate.beat_positions_ms.len());

    // Pattern is at 120 BPM (500ms intervals between events)
    // Allow tolerance: could detect 120 BPM or harmonics (60, 240)
    let is_tempo_reasonable = (estimate.bpm > 100.0 && estimate.bpm < 140.0)
        || (estimate.bpm > 55.0 && estimate.bpm < 65.0)   // half-time
        || (estimate.bpm > 230.0 && estimate.bpm < 250.0); // double-time

    assert!(is_tempo_reasonable,
        "Tempo {:.1} BPM is not near 120 BPM (or its harmonics 60/240)",
        estimate.bpm);
}

#[test]
fn test_pattern_full_pipeline() {
    let audio = load_test_wav("test-pattern.wav");

    // Step 1: Detect onsets
    let config = OnsetConfig::default();
    let onsets = audio::detect_onsets(&audio, &config);
    assert!(!onsets.is_empty(), "No onsets detected");

    // Step 2: Classify events
    let classifier = HeuristicClassifier::new();
    let window_duration_ms = 50.0;
    let mut events = Vec::new();
    for (i, onset) in onsets.iter().enumerate() {
        let features = audio::extract_features_for_window(&audio, onset.timestamp_ms, window_duration_ms);
        let result = classifier.classify(&features);
        let duration_ms = if i + 1 < onsets.len() {
            onsets[i + 1].timestamp_ms - onset.timestamp_ms
        } else {
            audio.duration_ms as f64 - onset.timestamp_ms
        };
        let event = events::Event::new(onset.timestamp_ms, duration_ms, result.class, result.confidence, features);
        events.push(event);
    }

    println!("Pipeline: {} events detected", events.len());

    // Step 3: Estimate tempo
    let tempo = groove::estimate_tempo(&onsets, audio.sample_rate);
    println!("Pipeline: tempo = {:.1} BPM", tempo.bpm);

    // Step 4: Quantize
    let grid = Grid::new_with_feel(tempo.bpm, TimeSignature::FourFour, GridDivision::Sixteenth, GrooveFeel::Straight, 0.0, 4);
    let settings = QuantizeSettings { strength: 0.8, swing_amount: 0.0, lookahead_ms: 100.0 };
    let quantized = groove::quantize_events(&events, &grid, &settings);

    println!("Pipeline: {} events quantized", quantized.len());
    for qe in &quantized {
        println!("  {:?} at {:.1}ms → {:.1}ms (delta={:.1}ms)",
            qe.original_event.class,
            qe.original_event.timestamp_ms,
            qe.quantized_timestamp_ms,
            qe.snap_delta_ms);
    }

    assert_eq!(quantized.len(), events.len(), "Quantized events count mismatch");

    // Step 5: Arrange
    let template = beatrice_lib::arranger::ArrangementTemplate::SynthwaveStraight;
    let arrangement = beatrice_lib::arranger::arrange_events(&quantized, &template, &grid, 0.6);

    let total_notes: usize = arrangement.all_lanes().iter().map(|l| l.events.len()).sum();
    println!("Pipeline: arrangement has {} lanes, {} total notes",
        arrangement.all_lanes().len(), total_notes);

    for lane in arrangement.all_lanes() {
        println!("  {} ({} notes)", lane.name, lane.events.len());
    }

    assert!(total_notes > 0, "Arrangement produced no notes");

    println!("\n=== FULL PIPELINE PASSED ===");
}
