// Beatrice - Beatbox to Synth Beat Generator
// Module declarations

use tauri::Manager;

pub mod arranger;
pub mod audio;
mod commands;
pub mod events;
pub mod groove;
mod pipeline;
mod state;
pub mod themes;

/// tauri-specta builder holding the full specta-annotated command set.
///
/// This is the single source of truth for the IPC surface: both the runtime
/// `invoke_handler` (see `run()`) and the `export_bindings` test derive from
/// it, so `src/bindings.ts` can never drift from the commands actually wired
/// into the app. Add a command here and it is exported and callable in one step.
fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
        commands::greet,
        commands::create_project,
        commands::get_project,
        commands::list_projects,
        commands::create_run,
        commands::get_run,
        commands::list_runs_for_project,
        commands::get_run_with_artifacts,
        commands::update_run_status,
        commands::create_artifact,
        commands::list_calibration_profiles,
        commands::create_calibration_profile,
        commands::get_calibration_profile,
        commands::update_calibration_profile,
        commands::delete_calibration_profile,
        commands::detect_onsets,
        commands::detect_events,
        commands::extract_features,
        commands::estimate_tempo,
        commands::quantize_events_command,
        commands::arrange_events_command,
        commands::export_midi_command,
        commands::list_themes,
        commands::get_theme,
        commands::list_theme_names,
        commands::start_recording,
        commands::stop_recording,
        commands::is_recording,
        commands::get_recording_level,
        commands::save_event_decisions,
        commands::get_event_decisions,
    ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        // tauri-specta's generated invoke handler. `invoke_handler(&self)`
        // returns an owned `'static` closure, so `builder` stays available to
        // move into the setup closure below for `mount_events`.
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            // Register tauri-specta event types (no-op today; keeps the router
            // authoritative if events are added later).
            builder.mount_events(app);

            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }

            // Initialize database
            let db = state::init_db()
                .map_err(|e| {
                    log::error!("Failed to initialize database: {}", e);
                    e
                })
                .expect("Failed to initialize database");

            // Add database to managed state
            app.manage(db);

            // Add recorder state
            app.manage(commands::RecorderState::default());

            log::info!("Beatrice initialized successfully");
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod bindings_test {
    use specta_typescript::BigIntExportBehavior;

    #[test]
    fn export_bindings() {
        super::specta_builder()
            .export(
                specta_typescript::Typescript::default()
                    // i64/u64 fields (e.g. `duration_ms`) are millisecond
                    // magnitudes well within JS `number` safe-integer range, so
                    // emit them as `number` rather than failing or using bigint.
                    .bigint(BigIntExportBehavior::Number)
                    .header("// @ts-nocheck — generated by tauri-specta; do not edit\n"),
                "../src/bindings.ts",
            )
            .expect("failed to export bindings");
    }
}
